### ISSUE TITLE
data base missing

### ISSUE THREAD

**Issue by smksamy** [vishalkhatal/UserManagementSystem#1]
Hi Bro,
Can you please add the SQL Quries

**Comment by vishalkhatal** [comment]
@smksamy 
I have already checked in the backup of the database. Please restore that backup on your local machine and then you can see the Store Proc used in the project. 
![image](https://user-images.githubusercontent.com/11478374/43235646-08cc94a4-909f-11e8-9df1-d1f9465738c8.png)
